### PR TITLE
Fix Linux Compiling - Part 2

### PR DESCRIPTION
**Pull request by iven**
现在应该可以编译了。

### CODE REVIEW

**Comment by WilliamShi** [comment]
../QSanguosha/src/server/roomthread.cpp:64:1: warning:   when initialized here [-Wreorder]
../QSanguosha/src/server/roomthread.cpp: In member function ‘void RoomThread::run3v3(QList<ServerPlayer*>&, QList<ServerPlayer*>&, GameRule_, ServerPlayer_)’:
../QSanguosha/src/server/roomthread.cpp:324:75: error: no matching function for call to ‘GameRule::trigger(TriggerEvent, Room_&, ServerPlayer_&, QVariant)’
../QSanguosha/src/server/roomthread.cpp:324:75: note: candidate is:
In file included from ../QSanguosha/src/server/roomthread.cpp:4:0:
../QSanguosha/src/server/gamerule.h:13:18: note: virtual bool GameRule::trigger(TriggerEvent, Room_, ServerPlayer_, QVariant&) const
../QSanguosha/src/server/gamerule.h:13:18: note:   no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
../QSanguosha/src/server/roomthread.cpp: In member function ‘void RoomThread::actionHulaoPass(ServerPlayer_, QList<ServerPlayer_>, GameRule_, int)’:
../QSanguosha/src/server/roomthread.cpp:457:83: error: no matching function for call to ‘GameRule::trigger(TriggerEvent, Room_&, ServerPlayer_&, QVariant)’
../QSanguosha/src/server/roomthread.cpp:457:83: note: candidate is:
In file included from ../QSanguosha/src/server/roomthread.cpp:4:0:
../QSanguosha/src/server/gamerule.h:13:18: note: virtual bool GameRule::trigger(TriggerEvent, Room_, ServerPlayer_, QVariant&) const
../QSanguosha/src/server/gamerule.h:13:18: note:   no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
../QSanguosha/src/server/roomthread.cpp:470:75: error: no matching function for call to ‘GameRule::trigger(TriggerEvent, Room_&, ServerPlayer_&, QVariant)’
../QSanguosha/src/server/roomthread.cpp:470:75: note: candidate is:
In file included from ../QSanguosha/src/server/roomthread.cpp:4:0:
../QSanguosha/src/server/gamerule.h:13:18: note: virtual bool GameRule::trigger(TriggerEvent, Room_, ServerPlayer_, QVariant&) const
../QSanguosha/src/server/gamerule.h:13:18: note:   no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
../QSanguosha/src/server/roomthread.cpp: In member function ‘void RoomThread::actionNormal(GameRule_)’:
../QSanguosha/src/server/roomthread.cpp:498:75: error: no matching function for call to ‘GameRule::trigger(TriggerEvent, Room_&, ServerPlayer_&, QVariant)’
../QSanguosha/src/server/roomthread.cpp:498:75: note: candidate is:
In file included from ../QSanguosha/src/server/roomthread.cpp:4:0:
../QSanguosha/src/server/gamerule.h:13:18: note: virtual bool GameRule::trigger(TriggerEvent, Room_, ServerPlayer_, QVariant&) const
../QSanguosha/src/server/gamerule.h:13:18: note:   no known conversion for argument 4 from ‘QVariant’ to ‘QVariant&’
make[1]: **\* [roomthread.o] Error 1
make[1]: Leaving directory `/home/hongwei/games/QSanguosha_build'
make: **\* [/home/hongwei/games/QSanguosha_build/QSanguosha] Error 2

**Comment by WilliamShi** [comment]
compile linux host:
 uname -a
Linux hwlinux 3.8.13-100.fc17.i686.PAE #1 SMP Mon May 13 13:45:03 UTC 2013 i686 i686 i386 GNU/Linux

**Comment by iven** [comment]
@WilliamShi Seems you haven't merged this commit?

**Comment by WilliamShi** [comment]
how to merge from another branch,I am newbie for git and when will it hit gaodayihao

**Comment by iven** [comment]
@WilliamShi For now you can use:

```
git clone --depth 1 git@github.com:iven/QSanguosha.git
```

to fetch the patched code.

And after this pull request is merged, you can use gaodayihao repository as before.

**Pull request merged**
